ALTER TABLE LOGEMENTENCADREMENTDESLOYERS
ADD CONSTRAINT FK_Quartier
FOREIGN KEY (NUMERO_INSEE_DU_QUARTIER) REFERENCES QUARTIERSADMINISTRATIFS(N_SQ_QU);

ALTER TABLE ARRONDISSEMENTS
ADD INDEX idx_N_SQ_CO (N_SQ_CO);

ALTER TABLE PLUESPACESLIBRESAVEGETALISERELV
ADD CONSTRAINT FK_Arrondissement_PluEspacesLibres
FOREIGN KEY (N_SQ_CA) REFERENCES ARRONDISSEMENTS(N_SQ_CO);

ALTER TABLE PLUESPACESVERTSPROTEGESEVP
ADD CONSTRAINT FK_Arrondissement_PluEspacesVertsProteges
FOREIGN KEY (N_SQ_PC) REFERENCES ARRONDISSEMENTS(N_SQ_CO);

ALTER TABLE QUARTIERSADMINISTRATIFS
ADD CONSTRAINT FK_Arrondissement_Quartier
FOREIGN KEY (N_SQ_AR) REFERENCES ARRONDISSEMENTS(IDENTIFIANT_SEQUENTIEL);

ALTER TABLE ETABLISSEMENTSSCOLAIRESMATERNELLES
ADD CONSTRAINT FK_Arrondissement_EtablissementsMaternelles
FOREIGN KEY (CODE_INSEE) REFERENCES ARRONDISSEMENTS(N_SQ_CO);

ALTER TABLE ETABLISSEMENTSSCOLAIRESELEMENTAIRES
ADD CONSTRAINT FK_Arrondissement_EtablissementsElementaires
FOREIGN KEY (CODE_INSEE) REFERENCES ARRONDISSEMENTS(N_SQ_CO);

ALTER TABLE ETABLISSEMENTSSCOLAIRESCOLLEGES
ADD CONSTRAINT FK_Arrondissement_EtablissementsColleges
FOREIGN KEY (CODE_INSEE) REFERENCES ARRONDISSEMENTS(N_SQ_CO);

ALTER TABLE ARRONDISSEMENTS
ADD INDEX idx_numero_arrondissement (NUMERO_ARRONDISSEMENT);

ALTER TABLE VALEURSFONCIERESPARIS2022
ADD CONSTRAINT FK_Arrondissement_ValeursFoncieres
FOREIGN KEY (NUMERO_ARRONDISSEMENT) REFERENCES ARRONDISSEMENTS(NUMERO_ARRONDISSEMENT);