CREATE TABLE ARRONDISSEMENTS (
    IDENTIFIANT_SEQUENTIEL INT PRIMARY KEY,
    NUMERO_ARRONDISSEMENT INT,
    NUMERO_ARRONDISSEMENT_INSEE INT,
    NOM_ARRONDISSEMENT VARCHAR(255),
    NOM_OFFICIEL_ARRONDISSEMENT VARCHAR(255),
    N_SQ_CO INT,
    SURFACE DECIMAL(20, 10),
    PERIMETRE DECIMAL(20, 10),
    GEOMETRY_X_Y VARCHAR(50),
    GEOMETRY GEOMETRY
);

CREATE TABLE VALEURSFONCIERESPARIS2022 (
    DATEMUTATION DATE,
    NATUREMUTATION VARCHAR(255),
    VALEURFONCIERE FLOAT,
    TYPEVOIE VARCHAR(255),
    CODEVOIE VARCHAR(255),
    VOIE VARCHAR(255),
    CODEPOSTAL VARCHAR(10),
    COMMUNE VARCHAR(255),
    CODEDEPARTEMENT VARCHAR(10),
    CODECOMMUNE NUMBER(10),
    TYPELOCAL VARCHAR(255),
    SURFACEREELLEBATI FLOAT,
    NOMBREPIECESPRINCIPALES FLOAT,
    SURFACETERRAIN FLOAT,
    NUMERO_ARRONDISSEMENT INT,
    FOREIGN KEY (NUMERO_ARRONDISSEMENT) REFERENCES ARRONDISSEMENTS(NUMERO_ARRONDISSEMENT)
);

CREATE TABLE LOGEMENTENCADREMENTDESLOYERS (
    ANNEE INT,
    SECTEURS_GEOGRAPHIQUES INT,
    NUMERO_DU_QUARTIER INT,
    NOM_DU_QUARTIER VARCHAR(50),
    NOMBRE_DE_PIECES_PRINCIPALES INT,
    EPOQUE_DE_CONSTRUCTION VARCHAR(20),
    TYPE_DE_LOCATION VARCHAR(20),
    LOYERS_DE_REFERENCE DECIMAL(10,2),
    LOYERS_DE_REFERENCE_MAJORES DECIMAL(10,2),
    LOYERS_DE_REFERENCE_MINORES DECIMAL(10,2),
    VILLE VARCHAR(255),
    NUMERO_INSEE_DU_QUARTIER INT,
    GEO_SHAPE GEOMETRY,
    GEO_POINT_2D VARCHAR(50),
    FOREIGN KEY (NUMERO_INSEE_DU_QUARTIER) REFERENCES QUARTIERSADMINISTRATIFS(N_SQ_QU)
);

CREATE TABLE PLUESPACESLIBRESAVEGETALISERELV (
    N_SQ_ELV INT,
    N_SQ_CA INT,
    N_SQ_PC INT,
    SHAPE_AREA DECIMAL(20, 10),
    SHAPE_LEN DECIMAL(20, 10),
    C_SEC VARCHAR(50),
    C_ASP VARCHAR(50),
    N_PC INT,
    GEO_SHAPE GEOMETRY,
    GEO_POINT VARCHAR(100)
);

CREATE TABLE PLUESPACESVERTSPROTEGESEVP (
    N_SQ_ELV INT PRIMARY KEY,
    N_SQ_ELV_1 INT,
    N_SQ_PC INT,
    CREATED_USER VARCHAR(100),
    CREATED_DATE DATE,
    LAST_EDITED_USER VARCHAR(100),
    LAST_EDITED_DATE DATE,
    SHAPE_AREA DECIMAL(20,10),
    SHAPE_LEN DECIMAL(20,10),
    GEO_SHAPE GEOMETRY,
    GEO_POINT_2D VARCHAR(50)
);

CREATE TABLE PLUSECTEURSDERISQUESDELIMITESPARLEPPRI (
    ZONAGE VARCHAR(100),
    N_SQ_PPRIZONE INT PRIMARY KEY,
    ST_AREA_SHAPE DECIMAL(20,10),
    ST_PERIMETER_SHAPE DECIMAL(20,10),
    GEO_SHAPE GEOMETRY,
    GEO_POINT_2D VARCHAR(50)
);

CREATE TABLE QUARTIERSADMINISTRATIFS (
    N_SQ_QU INT PRIMARY KEY,
    C_QU INT,
    C_QUINSEE INT,
    L_QU VARCHAR(100),
    C_AR INT,
    N_SQ_AR INT,
    PERIMETRE DECIMAL(20,10),
    SURFACE DECIMAL(20,10),
    GEOMETRY_X_Y VARCHAR(100),
    GEOMETRY GEOMETRY,
    ST_AREA_SHAPE DECIMAL(20,10),
    ST_PERIMETER_SHAPE DECIMAL(20,10)
);

CREATE TABLE ETABLISSEMENTSSCOLAIRESMATERNELLES (
    TYPE_ETABLISSEMENT_ANNEE_SCOLAIRE VARCHAR(255),
    LIBELLE_ETABLISSEMENT VARCHAR(255),
    ADRESSE VARCHAR(255),
    ARRONDISSEMENT VARCHAR(255),
    CODE_INSEE INT,
    ANNEE_SCOLAIRE VARCHAR(255),
    TYPE_ETABLISSEMENT VARCHAR(255),
    GEO_SHAPE GEOMETRY,
    GEO_POINT_2D VARCHAR(50),
    FOREIGN KEY (CODE_INSEE) REFERENCES ARRONDISSEMENTS(N_SQ_CO)
);

CREATE TABLE ETABLISSEMENTSSCOLAIRESELEMENTAIRES (
    TYPE_ETABLISSEMENT_ANNEE_SCOLAIRE VARCHAR(255),
    LIBELLE_ETABLISSEMENT VARCHAR(255),
    ADRESSE VARCHAR(255),
    ARRONDISSEMENT VARCHAR(255),
    CODE_INSEE INT,
    ANNEE_SCOLAIRE VARCHAR(255),
    TYPE_ETABLISSEMENT VARCHAR(255),
    CREATED_USER VARCHAR(100),
    CREATED_DATE DATE,
    LAST_EDITED_USER VARCHAR(100),
    LAST_EDITED_DATE DATE,
    GEO_SHAPE GEOMETRY,
    GEO_POINT_2D VARCHAR(50),
    FOREIGN KEY (CODE_INSEE) REFERENCES ARRONDISSEMENTS(N_SQ_CO)
);

CREATE TABLE ETABLISSEMENTSSCOLAIRESCOLLEGES (
    TYPE_ETABLISSEMENT_ANNEE_SCOLAIRE VARCHAR(255),
    LIBELLE_ETABLISSEMENT VARCHAR(255),
    ADRESSE VARCHAR(255),
    ARRONDISSEMENT VARCHAR(255),
    CODE_INSEE INT,
    ANNEE_SCOLAIRE VARCHAR(255),
    TYPE_ETABLISSEMENT VARCHAR(255),
    CREATED_USER VARCHAR(100),
    CREATED_DATE DATE,
    LAST_EDITED_USER VARCHAR(100),
    LAST_EDITED_DATE DATE,
    GEO_SHAPE GEOMETRY,
    GEO_POINT_2D VARCHAR(50),
    FOREIGN KEY (CODE_INSEE) REFERENCES ARRONDISSEMENTS(N_SQ_CO)
);