
SELECT q.N_SQ_QU, q.L_QU, l.LOYERS_DE_REFERENCE
FROM QUARTIERSADMINISTRATIFS q
INNER JOIN LOGEMENTENCADREMENTDESLOYERS l ON q.N_SQ_QU = l.NUMERO_INSEE_DU_QUARTIER;

SELECT a.NOM_ARRONDISSEMENT, p.SHAPE_AREA
FROM ARRONDISSEMENTS a
INNER JOIN PLUESPACESLIBRESAVEGETALISERELV p ON a.N_SQ_CO = p.N_SQ_CA;

SELECT a.NOM_ARRONDISSEMENT, p.SHAPE_AREA
FROM ARRONDISSEMENTS a
INNER JOIN PLUESPACESVERTSPROTEGESEVP p ON a.N_SQ_CO = p.N_SQ_PC;

SELECT q.N_SQ_QU, q.C_QU, q.C_QUINSEE, q.L_QU, a.NUMERO_ARRONDISSEMENT, a.NOM_ARRONDISSEMENT
FROM QUARTIERSADMINISTRATIFS q
INNER JOIN ARRONDISSEMENTS a ON q.N_SQ_AR = a.IDENTIFIANT_SEQUENTIEL;

SELECT a.NOM_ARRONDISSEMENT, e.LIBELLE_ETABLISSEMENT
FROM ARRONDISSEMENTS a
INNER JOIN ETABLISSEMENTSSCOLAIRESMATERNELLES e ON a.N_SQ_CO = e.CODE_INSEE;

SELECT a.NOM_ARRONDISSEMENT, e.LIBELLE_ETABLISSEMENT
FROM ARRONDISSEMENTS a
INNER JOIN ETABLISSEMENTSSCOLAIRESELEMENTAIRES e ON a.N_SQ_CO = e.CODE_INSEE;

SELECT a.NOM_ARRONDISSEMENT, e.LIBELLE_ETABLISSEMENT
FROM ARRONDISSEMENTS a
INNER JOIN ETABLISSEMENTSSCOLAIRESCOLLEGES e ON a.N_SQ_CO = e.CODE_INSEE;

SELECT a.NOM_ARRONDISSEMENT, v.VALEURFONCIERE
FROM ARRONDISSEMENTS a
INNER JOIN VALEURSFONCIERESPARIS2022 v ON a.NUMERO_ARRONDISSEMENT = v.NUMERO_ARRONDISSEMENT;
